name: epsilon-env
channels:
- conda-forge
- pyviz
- defaults
dependencies:
- python
- numpy
- scipy
- matplotlib
- pandas
- xarray
- seaborn
- gsw
- cmocean
- scikit-learn
- nb_conda_kernels
- ipykernel
- holoviews
- jupyter
- jupyterlab
- pyviz
- hvplot
- bokeh
- datashader
- dask
- bottleneck
